name: PR Workflow
on:
  pull_request:
    branches:
      - "**"

jobs:
  Get-Test-Results:
    name: Get the test results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
